controller:
  admin:
    username: "admin"
    password: "admin123"
  
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "400m"
      memory: "256Mi"

persistence:
  enabled: false

serviceAccount:
  create: true
  name: "jenkins"

installPlugins: false

service:
  type: ClusterIP
  port: 8080

agent:
  enabled: true
  defaultsProviderTemplate: "devops-tools"
  podTemplates:
    devops-tools: |
      - name: devops-tools
        label: devops-tools
        containers:
        - name: tools
          image: public.ecr.aws/aws-cli/aws-cli:latest
          command:
          - /bin/bash
          - -c
          args:
          - |
            yum install -y docker kubectl helm
            cat
          tty: true
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"