controller:
  admin:
    username: "admin"
    password: "admin123"
  
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "400m"
      memory: "256Mi"

persistence:
  enabled: false

serviceAccount:
  create: true
  name: "jenkins"

installPlugins: false

service:
  type: ClusterIP
  port: 8080

agent:
  enabled: true
  defaultsProviderTemplate: "devops-tools"
  podTemplates:
    devops-tools: |
      - name: devops-tools
        label: devops-tools
        containers:
        - name: tools
          image: public.ecr.aws/aws-cli/aws-cli:latest
          command:
          - /bin/bash
          - -c
          args:
          - |
            yum install -y docker kubectl helm
            cat
          tty: true
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
  
httpsKeyStore:
  enable: true
  httpPort: -1  # Disable HTTP
  port: 8443    # HTTPS port
  password: "changeit"
  jenkinsKeyStoreBase64Encoded: |-
      MIIKtgIBAzCCCmAGCSqGSIb3DQEHAaCCClEEggpNMIIKSTCCBbAGCSqGSIb3DQEHAaCCBaEEggWdMIIFmTCCBZUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFGeXYIcGETy6gONBnbb0ey/x63ClAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQLBR1iiPsQ7/GWetY22vWzgSCBND/6+dHFRVFPz3p1AUvHoNOFcYiv+MnmhVS8aEHXGsJiKVwi2cranGN8Pq9jhN6/Mc3spD7xBm5HmDIIuXqRUrlMII8WdCftNtOGI2l9UG2YS72iOzDTs7c6RJYmyoetpbonaG/dgN8xFjdMuSRfGUDNydXVB+Ti/VZCJ1MlKAIH/Op9HqOmm0h2mvRfkMy4Feu1VlfXguyNIoB4bP87CVHYrpcCZ2dpi8WDBS/j+Cw1uDM48kNeQioJrPynOVgXrVRqqzjyY6NwNdWz4KphiwyJpm5UuvG7Zw+Sv6YboBISyi8vMIhoePQWNzosX3PHCN8vVUJ4NpHoM7LYOcwVNiiLYTXauQYrJyQZ2XsCn260Jluo7QDWGexMEz87NexFxB84ue9IfMrkcVzGHQ+wIgD07Ry/20MGLMS1s4Ao93ycm0RAjIoyxicaUYApbRA4r1mmogbLOWAMBizJyWNu59xeqkCqd3N1ntQ6E5UO7ek2ni7KR/dX029TRBvf1/D66FLnfbQFM+/IMrXauVGahriF6UmTR2vFY8ucrqnJHGnhtmpljmW3hUVWqy1g92So7iXrOJCGq16DDHRYsh/fTCN4rEnT9JYdAwD2HL/hGM1k8YiwaFSuUzxc18v+Ph3cC22qOlA2xpSHWKwsBcqKqm49lGFcSbz78bcpny2+XPzn6bsAY8fVeH7yzO6A8Sune3S50CZ2PTB0swEaUyCNdG+jFn1ah9EaHoAOXnwIjzLJiMpnVk2xgOFkzgduKur1dxg6MIWFq1GlwmTGVwoLtJxSsixoq7IXzXHaj0rnPDXv7MsoRTiryRFNUT9rcWSuoXT4uLcpy56RTqj9pmJlrsvaP0mUVsNqweENdA5B+roPYzzLxResLtw3mCQssXkTVE/vp7bIJtdaxiNZvhY3pegW2R+q6egtrLt3FoRt6tFJPt8dFoCDIsaJPyVg7GJSTgV1WKAN3X5iCqX8mvi+wO1E6R67dycWc2AmFnQD2KE5Xdr/eVdiVPKHK6+3QV8pKaf2K15hbdeNpei+rCB1itaXFQSL9iasZZpZy+6DWeOOcYFN83yxgz0vbGjjMIqSJbdsolsZ6sOKFNQ4iN2yF85KNSimrni85Wisnx0JElEVmObDS9qW4qRdmOrwC4ptoinL2lpKor+/lqVqZGqykaqlY7SUvhRqu0zrdGHG769bDLQ33VWn9gjv2ffPnbwqCGCqJyGtdevZZN/fOCbsXuQJtWnTtK4xiahUaHts8zA4O898yAySTphU1BwKDu+fA1Nukg+cxBo8fCZ7nIEa/DcXN9LBysr7l058ZsEIwCgZeWM20NqHMSVWp7FWxThA7SNuPB/T+L+PXP/UQedrYzQExVrH43QUsBLasUJm8hPU5q6ovNabDJp95SBcS2whnY1KnIZhhsNBm2Y/jWHNEcXTtsMI5IIGIBsi76babC+terZPT03QeFOwzXReFnCxS7hxwZTTcfgvlB9n2fwEfwpPhHubtdE4nYMN3YgKqMn4L2b0MCf68Y16FMONcPBpx8H9iio0cDgaX68fb7ldakdMPWyImr4IkwgbOIeoUsT3LUxrKpbdkFD8legnSx3TKo05lwtzkPMQ5QuuhfwicmKKA83u5vRErm1avr0YnvEezFCMB0GCSqGSIb3DQEJFDEQHg4AagBlAG4AawBpAG4AczAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzM4OTYwMTIxOTIxMIIEkQYJKoZIhvcNAQcGoIIEgjCCBH4CAQAwggR3BgkqhkiG9w0BBwEwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFAPBO9dNWaXQvYHc565oo1KRyUBsAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ5bsbxisPtQUxA6CB4/FczoCCBADYvCLHnrtkRnxjZy8U0cgBwVS35DTvBL+F4F/FoG7f7MyTlANOJQdOWiA1B4WlYCv40btBuZOaYNSTXQDJjdJsri8DuWD0DIqtUP1P3R7c1nn9qy27P4t/gSHrL8ZlV29vb4BQB+zXUKZWfTtal9+7wWeyhWdObWcDnEf8A+LA3gWpdOQudbhdu1zWo0ywRMnaDZjnQB59iw13CohxOFMk/q509vF57aAJPrrRxwDs/xa9qx9krsg8A/pH/Ul1hXZt6Uy8kTA4jbUXQzOk6c+4jsiVXElgUI9UaDT7fGbP2K83D8jRIbo6wLQm7AUhydHcg5DOKTaGyhFZl3l8Ql1p1vXiYJE8YvOjRlDBP3/fab5PdnvN2c9O10oxrPYX//NmP2CACj2VnGqmt9p73TcquCggiwzWMWHaXUeGjpIRuu8+KxDLm917qtvNFC0SrYIhG1yFOLqig0LKNT8FY+cJXCTyV+W13upUCEpq98fDYG3iulCksJH5tJ+y6HQRgqMLO4FrMmzVoSrCagD5+yUubGp+47vBvjW2NNXAt1aMsjKLxMV1ksUz3k8VwmevIp1GkPqivxC2Pj2w3Aytx1nEX+n3onLMM3OqJ0zGMNxfMBmgQ2e/Ko61Sy+x0YRSZQAcqV+QkB/ZuwubnNQW16bSSL9z+Dfeit6F7lm640x6LebilgG0iyE04LgPxAe6h0QVBlzXJ6HpMtsiIGqvbHNuFoNgsIw99iT1qvMLy7toVR0WmCdRntvOoirFG9zUS9ReiTkU6bJObbYGdqSkr8J10INzkBmKSEN3NIEPIIb/x/FfyNGEAJRw4NfkEy6kGpepMYSi/FJPrsRdyqbGz725YVXs6z8wM5i5BkhwaZ3vZioP1olLWY2hHszB3qwkZFJraTxb6P7R+zIyjS/MoNS9SohfFTD8gbqVS6Vo/AiRfoeYQQRQSWoKlaYrolftdOjtHBsIzlpoEpJ8FxRXM1OspuEzxR06i26HANuEOCvF3RAWWvlRPeOiAEd8Yw+jw3NfFIv5YFAprlSLD1XPWvUiCc12PXmkkjDmYATkIISsutf2nq0+8wwRAdlLIrj+XSWWioA82scq/P2RYcD30ZoyOLRUUv93Z9iCkJjOtj+LU09UspwsrMd0mK3J8OdezzFXHtoUCuL73r7E1+HxVKG8pAlUhpHtUZwGf7datFu6DMwTRCG7ezYJApKcaDxq+NN9IfsFJVQ1Vu9XtUHoLNXscLGXFQuldtaJYyrERLgbw3v2iSrTqxeSEFD2HKvU0mS8KJmrud8dUim7P0KICuB1sOXgkBmpTt8IJFed9+ZR7FVuv8NFf747ngT3FymOFSO3+k6kU1xPfc41B1wXhWhDME0wMTANBglghkgBZQMEAgEFAAQgc+8xoTgw2TMtxUSJnSIvwWcthYQlBTsg++t3V4FGCYAEFJvJept2x5W7cgyDXvuVyqOJKC78AgInEA==
      
      
javaOpts: >-
    -Djenkins.install.runSetupWizard=false
    -Xmx2g
    -Xms512m
    -Dhudson.model.DirectoryBrowserSupport.CSP=
    -Djavax.net.ssl.trustStore=/var/jenkins_keystore/jenkins.jks
    -Djavax.net.ssl.trustStorePassword=changeit
    -Djavax.net.ssl.keyStore=/var/jenkins_keystore/jenkins.jks
    -Djavax.net.ssl.keyStorePassword=changeit
    
containerEnv:
  - name: JENKINS_UC
    value: https://updates.jenkins.io
  - name: JENKINS_UC_DOWNLOAD
    value: https://updates.jenkins.io/download
  - name: JENKINS_PLUGIN_INFO
    value: https://updates.jenkins.io/plugin-versions.json
      
JCasC:
  enabled: true
  configScripts:
      jenkins-configuration: |
        jenkins:
          updateCenter:
            sites:
            - id: "default"
              url: "https://updates.jenkins.io/update-center.json"
          proxy:
            name: ""
            port: 0
          disableRememberMe: true
          mode: NORMAL
          numExecutors: 0